// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniPos.Infrastructure.Persistence.Common;

#nullable disable

namespace OmniPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OmniPosDbContext))]
    [Migration("20251216161016_UpdateProduct")]
    partial class UpdateProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmniPos.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cà phê Robusta đậm đà truyền thống",
                            ImageUrl = "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=500&q=80",
                            IsArchived = false,
                            Name = "Cafe Đen Đá",
                            Price = 15000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sự hòa quyện giữa cafe đậm và sữa đặc",
                            ImageUrl = "https://images.unsplash.com/photo-1572286258217-202dbc1b581e?w=500&q=80",
                            IsArchived = false,
                            Name = "Cafe Sữa Đá",
                            Price = 20000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nhiều sữa ít cafe, vị ngọt dễ uống",
                            ImageUrl = "https://images.unsplash.com/photo-1582239682137-97d8b5986871?w=500&q=80",
                            IsArchived = false,
                            Name = "Bạc Xỉu",
                            Price = 25000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mát lạnh với miếng đào giòn tan",
                            ImageUrl = "https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?w=500&q=80",
                            IsArchived = false,
                            Name = "Trà Đào Cam Sả",
                            Price = 35000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Hương hoa hồng thơm nhẹ kết hợp vải thiều",
                            ImageUrl = "https://images.unsplash.com/photo-1621539207019-947702657e3f?w=500&q=80",
                            IsArchived = false,
                            Name = "Trà Vải Hoa Hồng",
                            Price = 35000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bánh sừng bò ngàn lớp thơm bơ",
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&q=80",
                            IsArchived = false,
                            Name = "Bánh Croissant",
                            Price = 28000m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bánh vị cafe và rượu rum",
                            ImageUrl = "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=500&q=80",
                            IsArchived = false,
                            Name = "Tiramisu",
                            Price = 40000m,
                            StockQuantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
